name: Deploy Azure
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on : ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker front image
      run: docker build . --file front/Dockerfile.prod --target production --tag '${{secrets.DOCKER_LOGIN}}'/front:latest  
    - name: Build the Docker backend image
      run: docker build . --file api/Dockerfile.prod --target production --tag '${{secrets.DOCKER_LOGIN}}'/backend:latest
    - name: Build the Docker ngnix image
      run: docker build . --file ngnix/Dockerfile --tag '${{secrets.DOCKER_LOGIN}}'/nginx:latest
    - name: Docker Login
      run: docker login --username '${secrets.DOCKER_LOGIN) --password '${{secrets.DOCKER_PASSWORD}}'
    - name: Push the Docker nginx image to Docker Hub
      run: doker push '${{secrets.DOCKER_LOGIN}}'/nginx:latest
    - name: Push the Docker backend image to Docker Hub
      run: doker push '${{secrets.DOCKER_LOGIN}}'/backend:latest
    - name: Push the Docker front image to Docker Hub
      run: doker push '${{secrets.DOCKER_LOGIN}}'/front:latest
